--- #YAML:1.0
name: JavaScript-RPC
version: 0.1
author:
  - Brian Cassidy <bricas@cpan.org>
abstract: Remote procedure calls from JavaScript
license: perl
provides:
  JavaScript::RPC::Server::CGI:
    file: lib/JavaScript/RPC/Server/CGI.pm
    version: 0.1
generated_by: Module::Build version 0.2611
